### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by scribu** [nb/oxymel#1]
Hello,

I'm requiring nb/oxymel in WP-CLI via Composer: wp-cli/wp-cli#525

Since it has no tags, I'm forced to use `dev-master` as the version spec, which might cause breakage in the future.

Could you push a tag, even if it's something like `v1.0-alpha`?

**Comment by nb** [comment]
Just pushed `v0.1.0`.

**Comment by scribu** [comment]
Thanks!
